src/main/java/com/fredfonseca/bookstoremanager/controller/BookController.java
=> Changed Controller for example

src/main/resources/application-dev.yml, src/main/resources/application-prod.yml
Added H2 configurations to the project
**READY**
Added H2 configurations to the project
```sh
http://localhost:8080/h2-console
```
=> Added H2 configurations to the project

src/main/java/com/fredfonseca/bookstoremanager/entity/Author.java, src/main/java/com/fredfonseca/bookstoremanager/entity/Book.java, src/main/java/com/fredfonseca/bookstoremanager/entity/Publisher.java, src/main/java/com/fredfonseca/bookstoremanager/entity/Users.java
**READY**
Created model mappings
```sh
http://localhost:8080/h2-console/login.do?jsessionid=4377a25471dbc5e3c162905b1ac0ef2c
```
=> Created model mappings

src/main/java/com/fredfonseca/bookstoremanager/entity/Author.java, src/main/java/com/fredfonseca/bookstoremanager/entity/Book.java, src/main/java/com/fredfonseca/bookstoremanager/entity/Publisher.java, src/main/java/com/fredfonseca/bookstoremanager/entity/Users.java, src/main/java/com/fredfonseca/bookstoremanager/entityauditable/Auditable.java
**READY**
Created auditable entity
```sh
[mvn spring-boot:run](http://localhost:8080/h2-console/login.do?jsessionid=4325bfdcb25746f6153ad50e55288934)
```
=> Created auditable entity

src/main/java/com/fredfonseca/bookstoremanager/author/repository/AuthorRepository.java, src/main/java/com/fredfonseca/bookstoremanager/books/repository/BookRepository.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/repository/PublisherRepository.java, src/main/java/com/fredfonseca/bookstoremanager/users/repository/UserRepository.java
**READY**
Created repository classes for entities
=> Created repository classes for entities

src/main/java/com/fredfonseca/bookstoremanager/controller/BookController.java, src/main/java/com/fredfonseca/bookstoremanager/exception/ApiError.java, src/main/java/com/fredfonseca/bookstoremanager/exception/BookstoreExceptionHandler.java
**READY**
Developed exception handler for the project
```sh
```
=> Developed exception handler for the project

pom.xml
**READY**
Added mapstruct configurationa
```sh
```
=> Added mapstruct configurationa

src/main/java/com/fredfonseca/bookstoremanager/author/dto/AuthorDTO.java
**READY**
Created Author DTO class
```sh
```
=> Created Author DTO class

src/main/java/com/fredfonseca/bookstoremanager/author/controller/AuthorController.java, src/main/java/com/fredfonseca/bookstoremanager/author/controller/AuthorControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/author/mapper/AuthorMapper.java, src/main/java/com/fredfonseca/bookstoremanager/author/service/AuthorService.java
**READY**
Created base authors structure classes
```sh
```
=> Created base authors structure classes

pom.xml
**READY**
Adda mapstruct configuration
```sh
```
=> Add mapstruct configuration

src/test/java/com/fredfonseca/bookstoremanager/author/builder/AuthorDTOBuilder.java, src/test/java/com/fredfonseca/bookstoremanager/author/controller/AuthorControllerTest.java, src/test/java/com/fredfonseca/bookstoremanager/author/service/AuthorServiceTest.java
**READY**
Created test structure class
```sh
```
=> Created test structure class

pom.xml, src/main/java/com/fredfonseca/bookstoremanager/author/controller/AuthorController.java, src/main/java/com/fredfonseca/bookstoremanager/author/controller/AuthorControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/author/dto/AuthorDTO.java, src/main/java/com/fredfonseca/bookstoremanager/author/entity/Author.java, src/main/java/com/fredfonseca/bookstoremanager/author/exception/AuthorAlreadyExistsException.java, src/main/java/com/fredfonseca/bookstoremanager/author/mapper/AuthorMapper.java, src/main/java/com/fredfonseca/bookstoremanager/author/repository/AuthorRepository.java, src/main/java/com/fredfonseca/bookstoremanager/author/service/AuthorService.java, src/main/java/com/fredfonseca/bookstoremanager/books/entity/Book.java, src/main/java/com/fredfonseca/bookstoremanager/books/repository/BookRepository.java, src/main/java/com/fredfonseca/bookstoremanager/config/SwaggerConfig.java, src/main/java/com/fredfonseca/bookstoremanager/controller/BookController.java, src/main/java/com/fredfonseca/bookstoremanager/entity/Auditable.java, src/main/java/com/fredfonseca/bookstoremanager/exception/ApiError.java, src/main/java/com/fredfonseca/bookstoremanager/exception/BookstoreExceptionHandler.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/entity/Publisher.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/repository/PublisherRepository.java, src/main/java/com/fredfonseca/bookstoremanager/users/entity/Users.java, src/main/java/com/fredfonseca/bookstoremanager/users/repository/UserRepository.java, src/main/resources/application.yml
**READY**
Fixing Swagger and merge
```sh
```
=> Fixing Swagger and merge

src/main/java/com/fredfonseca/bookstoremanager/author/controller/AuthorControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/author/entity/Author.java, src/main/java/com/fredfonseca/bookstoremanager/author/service/AuthorService.java, src/main/java/com/fredfonseca/bookstoremanager/entity/Auditable.java, src/main/resources/application.properties, src/main/resources/application.yml
**READY**
Developed author creation functionality
```sh
```
=> Developed author creation functionality

src/main/java/com/fredfonseca/bookstoremanager/author/controller/AuthorController.java, src/main/java/com/fredfonseca/bookstoremanager/author/controller/AuthorControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/author/dto/AuthorDTO.java, src/main/java/com/fredfonseca/bookstoremanager/author/exception/AuthorNotFoundException.java, src/main/java/com/fredfonseca/bookstoremanager/author/service/AuthorService.java
**READY**
Developed author by id functionality
```sh
```
=> Developed author by id functionality

src/main/java/com/fredfonseca/bookstoremanager/author/controller/AuthorController.java, src/main/java/com/fredfonseca/bookstoremanager/author/controller/AuthorControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/author/service/AuthorService.java
**READY**
Developed list authors feature
```sh
```
=> Developed list authors feature

src/main/java/com/fredfonseca/bookstoremanager/author/controller/AuthorController.java, src/main/java/com/fredfonseca/bookstoremanager/author/controller/AuthorControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/author/service/AuthorService.java
**READY**
Developed authors exclusion by id
```sh
```
=> Developed authors exclusion by id

src/main/java/com/fredfonseca/bookstoremanager/author/controller/AuthorController.java, src/main/java/com/fredfonseca/bookstoremanager/author/controller/AuthorControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/author/service/AuthorService.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/dto/PublisherDTO.java
**READY**
Created publisher DTO
```sh
```
=> Created publisher DTO

src/main/java/com/fredfonseca/bookstoremanager/publishers/controller/PublisherController.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/controller/PublisherControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/mapper/PublisherMapper.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/service/PublisherService.java
**READY**
Developed structure classes for publishers module
```sh
```
=> Developed structure classes for publishers module

src/main/java/com/fredfonseca/bookstoremanager/publishers/controller/PublisherController.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/controller/PublisherControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/exception/PublisherAlreadyExistsException.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/repository/PublisherRepository.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/service/PublisherService.java
**READY**
Developed publisher creation feature
```sh
```
=> Developed publisher creation feature

src/main/java/com/fredfonseca/bookstoremanager/publishers/controller/PublisherController.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/controller/PublisherControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/exception/PublisherNotFoundException.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/service/PublisherService.java
**READY**
Developed find publisher by id feature
```sh
```
=> Developed find publisher by id feature

src/main/java/com/fredfonseca/bookstoremanager/author/controller/AuthorControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/author/entity/Author.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/exception/PublisherAlreadyExistsException.java
**READY**
Fixing code typos and imports
```sh
```
=> Fixing code typos and imports

src/main/java/com/fredfonseca/bookstoremanager/publishers/controller/PublisherController.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/controller/PublisherControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/service/PublisherService.java
**READY**
Developed list publishers feature
```sh
```
=> Developed list publishers feature

src/main/java/com/fredfonseca/bookstoremanager/publishers/controller/PublisherController.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/controller/PublisherControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/service/PublisherService.java
**READY**
Developed publisher exclusion feature
```sh
```
=> Developed publisher exclusion feature

src/main/java/com/fredfonseca/bookstoremanager/publishers/controller/PublisherController.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/controller/PublisherControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/service/PublisherService.java
**READY**
Developed publisher update feature
```sh
```
=> Developed publisher update feature

src/main/java/com/fredfonseca/bookstoremanager/author/service/AuthorService.java
**READY**
Fixed author update feature
```sh
```
=> Fixed author update feature

src/main/java/com/fredfonseca/bookstoremanager/publishers/service/PublisherService.java
**READY**
Fixing publishers update
```sh
```
=> Fixing publishers update

src/main/java/com/fredfonseca/bookstoremanager/author/controller/AuthorController.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/controller/PublisherController.java
**READY**
Enabling cross origin for testing
```sh
```
=> Enabling cross origin for testing

src/main/java/com/fredfonseca/bookstoremanager/users/dto/UserDTO.java
**READY**
Created User DTO class
```sh
```
=> Created User DTO class

src/main/java/com/fredfonseca/bookstoremanager/users/controller/UserController.java, src/main/java/com/fredfonseca/bookstoremanager/users/controller/UserControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/users/mapper/UserMapper.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/UserService.java
**READY**
Developed base classes
```sh
```
=> Developed base classes

src/main/java/com/fredfonseca/bookstoremanager/users/dto/MessageDTO.java
**READY**
Created message DTO for users operation return message
```sh
```
=> Created message DTO for users operation return message

src/main/java/com/fredfonseca/bookstoremanager/users/controller/UserController.java, src/main/java/com/fredfonseca/bookstoremanager/users/controller/UserControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/users/entity/Users.java, src/main/java/com/fredfonseca/bookstoremanager/users/exception/UserAlreadyExistsException.java, src/main/java/com/fredfonseca/bookstoremanager/users/repository/UserRepository.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/UserService.java
**READY**
Developed user creation feature
```sh
```
=> Developed user creation feature

src/main/java/com/fredfonseca/bookstoremanager/users/controller/UserController.java, src/main/java/com/fredfonseca/bookstoremanager/users/controller/UserControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/users/exception/UserNotFoundException.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/UserService.java
**READY**
Users exclusion feature
```sh
```
=> Users exclusion feature

src/main/java/com/fredfonseca/bookstoremanager/users/controller/UserController.java, src/main/java/com/fredfonseca/bookstoremanager/users/controller/UserControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/UserService.java, src/main/java/com/fredfonseca/bookstoremanager/users/utils/MessageDTOUtils.java
**READY**
Developed users update feature
```sh
```
=> Developed users update feature

src/main/java/com/fredfonseca/bookstoremanager/author/service/AuthorService.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/service/PublisherService.java
**READY**
Refactor code and fix typos
```sh
```
=> Refactor code and fix typos

src/main/java/com/fredfonseca/bookstoremanager/users/controller/UserController.java, src/main/java/com/fredfonseca/bookstoremanager/users/controller/UserControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/UserService.java
**READY**
Developed get users
```sh
```
=> Developed get users

src/main/java/com/fredfonseca/bookstoremanager/config/PasswordEncodingConfig.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/UserService.java
**READY**
Added password encoding feature on users
```sh
```
=> Added password encoding feature on users

src/main/java/com/fredfonseca/bookstoremanager/author/entity/Author.java, src/main/java/com/fredfonseca/bookstoremanager/author/exception/AuthorNotFoundException.java, src/main/java/com/fredfonseca/bookstoremanager/books/controller/BookController.java, src/main/java/com/fredfonseca/bookstoremanager/books/controller/BookControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/books/dto/BookRequestDTO.java, src/main/java/com/fredfonseca/bookstoremanager/books/entity/Book.java, src/main/java/com/fredfonseca/bookstoremanager/books/exception/BookAlreadyExistsException.java, src/main/java/com/fredfonseca/bookstoremanager/books/repository/BookRepository.java, src/main/java/com/fredfonseca/bookstoremanager/books/service/BookService.java, src/main/java/com/fredfonseca/bookstoremanager/config/AuditConfig.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/exception/PublisherNotFoundException.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/service/PublisherService.java
**READY**
Developed books creation feature
```sh
```
=> Developed books creation feature

src/main/java/com/fredfonseca/bookstoremanager/books/controller/BookController.java, src/main/java/com/fredfonseca/bookstoremanager/books/controller/BookControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/books/exception/BookNotFoundException.java, src/main/java/com/fredfonseca/bookstoremanager/books/service/BookService.java
**READY**
Developed book by id feature
```sh
```
=> Developed book by id feature

src/main/java/com/fredfonseca/bookstoremanager/books/controller/BookController.java, src/main/java/com/fredfonseca/bookstoremanager/books/controller/BookControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/books/service/BookService.java
**READY**
Developed books listing feature
```sh
```
=> Developed books listing feature

src/main/java/com/fredfonseca/bookstoremanager/books/controller/BookController.java, src/main/java/com/fredfonseca/bookstoremanager/books/controller/BookControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/books/service/BookService.java
**READY**
Developed feature for books exclusion
```sh
```
=> Developed feature for books exclusion

src/main/java/com/fredfonseca/bookstoremanager/books/entity/Book.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/entity/Publisher.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/controller/RentalController.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/controller/RentalControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/dto/RentalRequestDTO.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/dto/RentalResponseDTO.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/entity/Rental.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/mapper/RentalMapper.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/repository/RentalRepository.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/service/RentalService.java, src/main/java/com/fredfonseca/bookstoremanager/users/entity/Users.java
**READY**
Created rentals classes
```sh
```
=> Created rentals classes

src/main/java/com/fredfonseca/bookstoremanager/rentals/controller/RentalController.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/controller/RentalControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/RentalNotFoundException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/service/RentalService.java
**READY**
Developed GETs paths for rentals
```sh
```
=> Developed GETs paths for rentals

src/main/java/com/fredfonseca/bookstoremanager/rentals/controller/RentalController.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/controller/RentalControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/service/RentalService.java
**READY**
Developed rentals delete feature
```sh
```
=> Developed rentals delete feature

src/main/java/com/fredfonseca/bookstoremanager/books/dto/BookResponseDTO.java, src/main/java/com/fredfonseca/bookstoremanager/books/entity/Book.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/InvalidBookQuantity.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/service/RentalService.java
**READY**
Books quantity validation feature
```sh
```
=> Books quantity validation feature

src/main/java/com/fredfonseca/bookstoremanager/rentals/dto/RentalRequestDTO.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/entity/Rental.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/EmptyReturnDateException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/InvalidDateException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/InvalidReturnDateException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/service/RentalService.java
=> Feature: Developed rentals update implementing return date

src/main/java/com/fredfonseca/bookstoremanager/books/repository/BookRepository.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/dto/PublisherDTO.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/controller/RentalControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/dto/RentalRequestDTO.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/service/RentalService.java, src/main/java/com/fredfonseca/bookstoremanager/users/controller/UserController.java, src/main/java/com/fredfonseca/bookstoremanager/users/dto/UserDTO.java
**READY**
Cleaning code and unused imports
```sh
```
=> Refactor: cleaning code and unused imports

src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/InvalidReturnDateException.java
**READY**
Preparing for realease
```sh
```
=> Preparing for release

src/main/java/com/fredfonseca/bookstoremanager/config/JwtAuthenticationLvlDenied.java, src/main/java/com/fredfonseca/bookstoremanager/config/WebSecurityConfig.java
**READY**
Finished security configuration feature
```sh
```
=> Finished security configuration feature

src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/InvalidDateException.java
**READY**
Fixing invalid date exception message from rentals
```sh
```
=> fixes:invalid date exception message

src/main/java/com/fredfonseca/bookstoremanager/users/exception/InvalidCredentialsChange.java, src/main/java/com/fredfonseca/bookstoremanager/users/exception/UserAlreadyExistsException.java, src/main/java/com/fredfonseca/bookstoremanager/users/exception/UserEmailAlreadyExistsException.java, src/main/java/com/fredfonseca/bookstoremanager/users/exception/UserNotFoundException.java, src/main/java/com/fredfonseca/bookstoremanager/users/exception/UsernameAlreadyExistsException.java
**READY**
Updating users exceptions
```sh
```
=> Updating exceptions +

src/main/java/com/fredfonseca/bookstoremanager/users/service/UserService.java
**READY**
Update users entity service
```sh
```
=> Update:update users entity service

src/main/java/com/fredfonseca/bookstoremanager/books/exception/InvalidDateException.java
**READY**
Fixing books exception message on Launch date
```sh
```
=> Fixing books exception message on Launch date

src/main/java/com/fredfonseca/bookstoremanager/books/entity/Book.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/entity/Publisher.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/dto/RentalResponseDTO.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/entity/Rental.java, src/main/java/com/fredfonseca/bookstoremanager/users/entity/Users.java
**READY**
Updating entities relationships
```sh
```
=> Updating entities relationships

src/main/java/com/fredfonseca/bookstoremanager/rentals/controller/RentalController.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/controller/RentalControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/RentalAlreadyExistsException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/RentalChangeNotAllowedException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/RentalCreationNotAllowed.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/repository/RentalRepository.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/service/RentalService.java, src/main/java/com/fredfonseca/bookstoremanager/users/exception/UserNotFoundException.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/UserService.java
**READY**
Finished rentals security integration
```sh
```
=> Finished rentals security integration

src/main/java/com/fredfonseca/bookstoremanager/books/dto/BookRequestDTO.java, src/main/java/com/fredfonseca/bookstoremanager/books/dto/BookResponseDTO.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/controller/PublisherController.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/controller/PublisherControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/dto/PublisherRequestDTO.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/dto/PublisherResponseDTO.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/mapper/PublisherMapper.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/service/PublisherService.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/dto/RentalResponseDTO.java, src/main/java/com/fredfonseca/bookstoremanager/users/dto/UserDTO.java, src/main/java/com/fredfonseca/bookstoremanager/users/exception/UserCredentialsChangeNotAllowed.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/UserService.java
**READY**
Refactoring DTOs and adjusting entry data
```sh
```
=> Refactor:update DTOs

src/main/java/com/fredfonseca/bookstoremanager/config/WebSecurityConfig.java, src/main/java/com/fredfonseca/bookstoremanager/users/controller/UserController.java, src/main/java/com/fredfonseca/bookstoremanager/users/controller/UserControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/users/dto/UserDTO.java, src/main/java/com/fredfonseca/bookstoremanager/users/exception/DeleteDeniedException.java, src/main/java/com/fredfonseca/bookstoremanager/users/exception/InvalidCredentialsChange.java, src/main/java/com/fredfonseca/bookstoremanager/users/repository/UserRepository.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/JwtTokenManager.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/UserService.java, src/main/resources/application.properties
**READY**
Added security to users entity
```sh
```
=> Added security to users entity

src/main/java/com/fredfonseca/bookstoremanager/books/controller/BookController.java, src/main/java/com/fredfonseca/bookstoremanager/books/controller/BookControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/books/service/BookService.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/controller/PublisherController.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/controller/PublisherControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/service/PublisherService.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/controller/RentalController.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/controller/RentalControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/repository/RentalRepository.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/service/RentalService.java, src/main/java/com/fredfonseca/bookstoremanager/users/controller/UserController.java, src/main/java/com/fredfonseca/bookstoremanager/users/controller/UserControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/UserService.java
**READY**
Added pagination to GET endpoints
```sh
```
=> Added pagination to GET endpoints

src/main/java/com/fredfonseca/bookstoremanager/config/JwtRequestFilter.java, src/main/java/com/fredfonseca/bookstoremanager/exception/BookstoreExceptionHandler.java
**READY**
Handle unauthorized exceptions
```sh
```
=> handle unauthorized exceptions

src/main/java/com/fredfonseca/bookstoremanager/config/JwtAuthenticationEntryPoint.java, src/main/java/com/fredfonseca/bookstoremanager/config/JwtAuthenticationLvlDenied.java, src/main/java/com/fredfonseca/bookstoremanager/exception/BookstoreExceptionHandler.java
**READY**
Format unauthorized and forbidden messages
```sh
```
=> Format unauthorized and forbidden messages

src/main/resources/application.properties
**READY**
Increase session time to 10min
```sh
```
=> Change session time to 10min

src/main/java/com/fredfonseca/bookstoremanager/publishers/entity/Publisher.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/dto/RentalRequestDTO.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/service/RentalService.java, src/main/java/com/fredfonseca/bookstoremanager/users/controller/UserController.java, src/main/java/com/fredfonseca/bookstoremanager/users/controller/UserControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/UserService.java
**READY**
Removing unnecessary code
```sh
```
=> refactor:removing unnecessary code

src/main/java/com/fredfonseca/bookstoremanager/config/WebSecurityConfig.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/entity/Publisher.java
**READY**
Removing rental's access to unauthenticated users
```sh
```
=> Removing rental's access to unauthenticated users

bookstore_manager.postman_collection
**READY**
Upload postman paths to tests
```sh
```
=> Upload postman paths to tests

src/main/java/com/fredfonseca/bookstoremanager/publishers/service/PublisherService.java
=> eliminating duplicate code

src/main/java/com/fredfonseca/bookstoremanager/books/entity/Book.java, src/main/java/com/fredfonseca/bookstoremanager/books/service/BookService.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/entity/Publisher.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/service/PublisherService.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/entity/Rental.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/service/RentalService.java, src/main/java/com/fredfonseca/bookstoremanager/users/entity/Users.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/UserService.java
**READY**
Cleaning code and fixing if statements
```sh
```
=> refactor: remove bad code

src/main/java/com/fredfonseca/bookstoremanager/users/service/UserService.java
**READY**
Fix rules for admin update
```sh
```
=> fix: users admin rules

src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/BookAlreadyReturnedException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/service/RentalService.java
Return book to stock on delete and on return feature
```sh
```
=> feat: return book to stock on delete and on return

src/main/java/com/fredfonseca/bookstoremanager/rentals/enums/RentalReturnStates.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/service/RentalService.java
**READY**
Added enums in rental service
```sh
```
=> feat: added enums in rental service

src/main/java/com/fredfonseca/bookstoremanager/rentals/controller/RentalController.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/controller/RentalControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/service/RentalService.java
**READY**
Implement rent creation rule for admin and users
```sh
```
=> fix: rent creation by admin and user

src/main/java/com/fredfonseca/bookstoremanager/users/exception/DeleteDeniedException.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/UserService.java
**READY**
Rule logged user cannot delete itself feature
```sh
```
=> feat: logged user cannot delete itself

src/main/java/com/fredfonseca/bookstoremanager/users/controller/UserController.java, src/main/java/com/fredfonseca/bookstoremanager/users/controller/UserControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/users/dto/RecoverUserInfo.java, src/main/java/com/fredfonseca/bookstoremanager/users/repository/UserRepository.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/RecoverUserDataService.java
**READY**
Implement user recover password feature
```sh
```
=> feat: user password recover

bookstoremanagerapi.postman_collection
=> Upload postman api routes

src/main/java/com/fredfonseca/bookstoremanager/config/JwtAuthenticationEntryPoint.java, src/main/java/com/fredfonseca/bookstoremanager/config/JwtRequestFilter.java
=> fix: unauthorized users that changed token info

src/main/java/com/fredfonseca/bookstoremanager/config/WebSecurityConfig.java, src/main/java/com/fredfonseca/bookstoremanager/users/controller/UserController.java, src/main/java/com/fredfonseca/bookstoremanager/users/controller/UserControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/users/dto/AdminDTO.java, src/main/java/com/fredfonseca/bookstoremanager/users/dto/UserResponseDTO.java, src/main/java/com/fredfonseca/bookstoremanager/users/mapper/UserMapper.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/UserService.java
=> fix: fix authentication

src/main/java/com/fredfonseca/bookstoremanager/books/service/BookService.java, src/main/java/com/fredfonseca/bookstoremanager/utils/StringPattern.java
=> feat: book name validator

src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/InvalidFutureDateException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/service/RentalService.java, src/main/java/com/fredfonseca/bookstoremanager/utils/StringPattern.java
=> fix: fix string pattern

Bookstore Manager.postman_collection.json
**READY**
Postman file
```sh
```
=> docs: postman file

src/main/java/com/fredfonseca/bookstoremanager/books/entity/Book.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/entity/Publisher.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/entity/Rental.java, src/main/java/com/fredfonseca/bookstoremanager/users/entity/Users.java
=> fix: update attributes length

src/main/java/com/fredfonseca/bookstoremanager/books/service/BookService.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/UserService.java
=> fix: validation

src/main/java/com/fredfonseca/bookstoremanager/books/exception/BookAlreadyExistsException.java, src/main/java/com/fredfonseca/bookstoremanager/books/exception/BookNotFoundException.java, src/main/java/com/fredfonseca/bookstoremanager/books/exception/DeleteDeniedException.java, src/main/java/com/fredfonseca/bookstoremanager/books/exception/InvalidDateException.java, src/main/java/com/fredfonseca/bookstoremanager/books/exception/InvalidQuantityException.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/exception/DeleteDeniedException.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/exception/PublisherAlreadyExistsException.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/exception/PublisherNotFoundException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/BookAlreadyReturnedException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/InvalidBookQuantity.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/InvalidDateException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/InvalidPatDateException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/InvalidReturnDateException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/RentalAlreadyExistsException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/RentalChangeNotAllowedException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/RentalNotFoundException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/service/RentalService.java, src/main/java/com/fredfonseca/bookstoremanager/users/exception/DeleteDeniedException.java, src/main/java/com/fredfonseca/bookstoremanager/users/exception/InvalidCredentialsChange.java, src/main/java/com/fredfonseca/bookstoremanager/users/exception/UserEmailAlreadyExistsException.java, src/main/java/com/fredfonseca/bookstoremanager/users/exception/UserNotFoundException.java, src/main/java/com/fredfonseca/bookstoremanager/users/exception/UsernameAlreadyExistsException.java
**READY**
Translate api exceptions message
```sh
```
=> fix: translate api exceptions message

src/main/java/com/fredfonseca/bookstoremanager/users/dto/RecoverUserInfo.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/RecoverUserDataService.java
=> feat: add new password function to recover user data info

src/main/java/com/fredfonseca/bookstoremanager/config/WebSecurityConfig.java
=> fix: add cors to secured endpoints

src/main/java/com/fredfonseca/bookstoremanager/books/service/BookService.java
=> fix: book update rented quantity

src/main/java/com/fredfonseca/bookstoremanager/books/service/BookService.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/service/PublisherService.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/UserService.java, src/main/java/com/fredfonseca/bookstoremanager/utils/StringPattern.java
=> feat: add strings validation

src/main/java/com/fredfonseca/bookstoremanager/utils/StringPattern.java
=> fix: allow accents

src/main/java/com/fredfonseca/bookstoremanager/config/WebSecurityConfig.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/controller/RentalController.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/controller/RentalControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/RentalChangeNotAllowedException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/repository/RentalRepository.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/service/RentalService.java, src/main/java/com/fredfonseca/bookstoremanager/users/dto/AdminDTO.java, src/main/java/com/fredfonseca/bookstoremanager/users/exception/DeleteDeniedException.java, src/main/java/com/fredfonseca/bookstoremanager/users/repository/UserRepository.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/RecoverUserDataService.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/UserService.java
=> final push

src/main/java/com/fredfonseca/bookstoremanager/config/WebSecurityConfig.java
=> fix: allow rentals get endpoint

src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/RentalAlreadyExistsException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/service/RentalService.java
=> fix: users rentals rules

src/main/java/com/fredfonseca/bookstoremanager/rentals/controller/RentalController.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/controller/RentalControllerDocs.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/InvalidPastDateException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/InvalidPatDateException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/service/RentalService.java
=> feat: implement adtional rental edit

src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/InvalidPastDateException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/exception/InvalidRentalDateException.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/service/RentalService.java
=> fix: add rental past date limit

src/main/java/com/fredfonseca/bookstoremanager/rentals/service/RentalService.java
=> fix: rental date validation

src/main/java/com/fredfonseca/bookstoremanager/books/dto/BookResponseDTO.java, src/main/java/com/fredfonseca/bookstoremanager/books/entity/Book.java, src/main/java/com/fredfonseca/bookstoremanager/books/service/BookService.java, src/main/java/com/fredfonseca/bookstoremanager/config/WebConfiguration.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/dto/PublisherResponseDTO.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/entity/Publisher.java, src/main/java/com/fredfonseca/bookstoremanager/publishers/service/PublisherService.java, src/main/java/com/fredfonseca/bookstoremanager/rentals/entity/Rental.java, src/main/java/com/fredfonseca/bookstoremanager/users/dto/UserResponseDTO.java, src/main/java/com/fredfonseca/bookstoremanager/users/entity/Users.java, src/main/java/com/fredfonseca/bookstoremanager/users/service/UserService.java
=> fix: pagination size
